* pyza
=pyza= is a command-line (or terminal, or console, or whatever you want to call it) Songza player, originally based on [[https://github.com/robu3/mixzatape][MixZaTape]].  It can use VLC to play audio in a subprocess in the background, or send tracks to an MPD server to play.  It runs best on Linux, but you can probably run it on OS X, and you might be able to get it working on Windows.

** Requirements
+ Python 2.7+ (it might work on 2.6...)
+ VLC or MPD
+ MPD support requires =python-mpd= >= version 0.5.4.  This is from the forked version known as =python-mpd2=, which may not be packaged in your distro yet.  You can install it with =pip=.

** Usage
It's pretty self-explanatory:

#+BEGIN_SRC
usage: pyza [-h]
            [-l [{activities,genres,decades,moods} [{activities,genres,decades,moods} ...]]]
            [-e [QUERY [QUERY ...]]] [-f] [-d] [-n] [-m [HOST[:PORT]]] [-r]
            [-R] [--sort {name,songs,id}] [-v]
            [STATION/QUERY [STATION/QUERY ...]]

A terminal-based Songza client. Plays with VLC by default. Queries may be
plain queries which will match against station names and descriptions, or they
may be in the form of {activity|a,genre|g,mood|m}:query to search for stations
by activity, genre, or mood. For example: "pyza -f reading" or "pyza -f
genre:jazz" or "pyza -f m:happy"

positional arguments:
  STATION/QUERY         A station name, partial station name, or station ID
                        number

optional arguments:
  -h, --help            show this help message and exit
  -l [{activities,genres,decades,moods} [{activities,genres,decades,moods} ...]], --list-categories [{activities,genres,decades,moods} [{activities,genres,decades,moods} ...]]
                        Display list of available categories
  -e [QUERY [QUERY ...]], --exclude [QUERY [QUERY ...]]
                        Exclude stations matching queries
  -f, --find            List stations matching queries
  -d, --descriptions    Show station descriptions
  -n, --names-only      Only search station names, not station descriptions or
                        other data
  -m [HOST[:PORT]], --mpd [HOST[:PORT]]
                        Play with MPD server. Default: localhost:6600
  -r, --random          Play one random station matching query
  -R, --random-stations
                        Play one song each from random stations matching
                        queries
  --sort {name,songs,id}
                        Sort station list. Default: number of songs
  -v, --verbose         Be verbose, up to -vv
#+END_SRC
** Examples
=pyza.py -R piano jazz -e christmas= would play one track at a time from random "jazz" and "piano" stations, but not Christmas stations.

=pyza.py -f g:jazz= would list stations from the jazz genre.

=pyza.py -n -s under\ the\ boardwalk= would play the station "Under the Boardwalk".  If you left off =-n=, it would instead list multiple stations, because it would also search on station descriptions.  (You can--and should--quote strings instead of escaping the spaces, but due to a problem in the parser for this readme file, quotes don't work within code strings.  Doh...)

** TODOs
+ Use signals or something to allow skipping tracks and voting.
+ Somehow provide access to the Songza concierge service?
+ +Allow searching by activity, genre, or mood.+

** Credits
+ Thanks to [[https://github.com/TannerBaldus][TannerBaldus]] for writing most of the code for querying activities, genres, and moods.
+ Thanks to robu3 for creating [[https://github.com/robu3/mixzatape][MixZaTape]], which inspired =pyza=.

** License
GPLv2
