* pyza
=pyza= is a command-line (or terminal, or console, or whatever you want to call it) Songza player, originally based on [[https://github.com/robu3/mixzatape][MixZaTape]].  It can use VLC to play audio in a subprocess in the background, or send tracks to an MPD server to play.  It runs best on Linux, but you can probably run it on OS X, and you might be able to get it working on Windows.

** Requirements
+ Python 2.7+ (it might work on 2.6...)
+ VLC or MPD
+ MPD support requires =python-mpd= >= version 0.5.4.  This is from the forked version known as =python-mpd2=, which may not be packaged in your distro yet.  You can install it with =pip=.
+ [[http://deron.meranda.us/python/demjson/][python-demjson]] It's packaged in Debian/Ubuntu, or you can install with =pip install demjson=.
  
** Usage
It's pretty self-explanatory:

#+BEGIN_SRC
usage: pyza.py [-h]
               [-l [{activities,genres,moods} [{activities,genres,moods} ...]]]
               [-e [QUERY [QUERY ...]]] [-f [QUERY [QUERY ...]]] [-n]
               [-m [HOST[:PORT]]] [-r [QUERY [QUERY ...]]]
               [-R [QUERY [QUERY ...]]] [-s [STATION [STATION ...]]]
               [--sort {name,songs,id}] [-v]

A terminal-based Songza client. Plays with VLC by default. Queries may be
plain queries which will match against station names and descriptions, or they
may be in the form of {activity|a,genre|g,mood|m}:query to search for stations
by activity, genre, or mood. For example: "pyza -f reading" or "pyza -f genre:jazz"
or "pyza -f m:happy"

optional arguments:
  -h, --help            show this help message and exit
  -l [{activities,genres,moods} [{activities,genres,moods} ...]], --list-categories [{activities,genres,moods} [{activities,genres,moods} ...]]
                        Display list of available categories
  -e [QUERY [QUERY ...]], --exclude [QUERY [QUERY ...]]
                        Exclude stations matching queries
  -f [QUERY [QUERY ...]], --find [QUERY [QUERY ...]]
                        List stations matching queries
  -n, --names-only      Only search station names, not station descriptions or
                        other data
  -m [HOST[:PORT]], --mpd [HOST[:PORT]]
                        Play with MPD server. Default: localhost:6600
  -r [QUERY [QUERY ...]], --random [QUERY [QUERY ...]]
                        Play one random station matching query
  -R [QUERY [QUERY ...]], --random-stations [QUERY [QUERY ...]]
                        Play one song each from random stations matching
                        queries
  -s [STATION [STATION ...]], --station [STATION [STATION ...]]
                        A station name, partial station name, or station ID
                        number
  --sort {name,songs,id}
                        Sort station list. Default: number of songs
  -v, --verbose         Be verbose, up to -vv
#+END_SRC
** Examples
=pyza.py -R piano jazz -e christmas= would play one track at a time from random "jazz" and "piano" stations, but not Christmas stations.

=pyza.py -f g:jazz= would list stations from the jazz genre.

=pyza.py -n -s under\ the\ boardwalk= would play the station "Under the Boardwalk".  If you left off =-n=, it would instead list multiple stations, because it would also search on station descriptions.  (You can--and should--quote strings instead of escaping the spaces, but due to a problem in the parser for this readme file, quotes don't work within code strings.  Doh...)

** TODOs
+ Use signals or something to allow skipping tracks and voting.
+ Allow searching by mood, concierge, or some of the other things Songza has.
  
** License
GPLv2
